name: holy_quran_app
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  awesome_dialog: ^3.2.1
  flutter:
    sdk: flutter
  flutter_onboarding_slider: ^1.0.11
  flutter_advanced_drawer: ^1.3.6
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  http: ^1.2.2
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3+1
  provider: ^6.1.2
  connectivity_plus: ^6.0.5
  flutter_launcher_icons: ^0.14.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri/Amiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/Amiri/Amiri-Italic.ttf
          style: italic

  assets:
    - assets/images/
    - assets/icons/
